
paths:
    root: /work/audio_classification/thumos14/experiments
    db_data: /work/audio_classification/thumos14/experiments/data
    code: /work/Dropbox/audio_classification/source/action_nick/Code_v0.2
    yael: /work/Dropbox/audio_classification/source/action_nick/Code_v0.2/external_packages/yael_v438/matlab
    LibSvm: /work/Dropbox/audio_classification/source/action_nick/Code_v0.2/external_packages/libsvm-3.17/matlab
    class_list: /work/Dropbox/audio_classification/thumos14/detection_audio_classInd.txt.selection
    clip_list: /work/Dropbox/audio_classification/thumos14/detection_clips_audio.txt.selection
    db: /work/databases/thumos14_local
    features: /work/audio_classification/thumos14/features/mfcc25
    ucf101_config: /work/Dropbox/audio_classification/source/action_nick/Code_v0.2/configs/audio_UCF101_thumos14_local.yaml


DEBUG: 0
dbName: thumos14
global_seed: 25

# feature parameters
features:
    type: DT
    executable: /rmt8/mobot/external_packages/dense_trajectories/dense_trajectory_release_v1.2/release/DenseTrack
    libs: /rmt8/mobot/external_packages/opencv/lib/:/rmt8/mobot/external_packages/ffmpeg/ffmpeg_build/lib/ 
    descriptors: [mfcc25]
    L: 15 # trajectory length
    W: 5 # sampling stride
    N: 32 # neighbourhood size
    s: 2 # number of spatial cells
    t: 3 # number of temporal cells
    save2disk: 1
    # the following flag is experimental, use only with Hollywood2 dataset, and not in a parfor loop!
    use_disk: 0
    
# encoding parameters
encoding:
    type: BoVW # possible options are BoVW, vlad or fisher
    K: 100 # MODIFY!!! number of visual words for either kmeans or gmm
    data_usage: 20000 # data used for codebook generation as percentage of TrainData
    pca_factor: 1
    num_seeds: 1 # number of k-means repetitions with different (random) initializations (seeds)


# classification parameters
classification:
    svm_cost: 100
    kernel: ChiSquared #linear ChiSquared
    combine: 0
    combine_descriptors: [] # MODIFY!!! think possible combinations
    
# possible reusage of elements
reuse:
    features: 1

## states
# 0: nothing has been done
# 1: codebook has been generated
# 2: encodings have been computed
# 2.5: kernels have been computed (does not apply to Linear kernel)
# 3: SVMs have been trained
# 4: testinghas been done
state: 0

