
paths:
    root: /rmt/work/irodoma/audio_asr/classification/ucf101/experiments_mfcc25
    db: /rmt8/databases/UCF101
    db_data: /rmt/work/irodoma/audio_asr/classification/ucf101/experiments_mfcc25/data
    code: /rmt/work/irodoma/audio_asr/classification/source/action_nick/Code_v0.2
    yael: /rmt8/mobot/external_packages/yael/yael_v438/matlab
    LibSvm: /rmt8/mobot/external_packages/libsvm-3.17/matlab
    features: /rmt/work/irodoma/audio_asr/classification/ucf101/features/mfcc25 # mat files with features.mfcc (e.g. nFrames x 39) 
    class_list: /rmt/work/irodoma/audio_asr/classification/ucf101/audio_classInd.txt
    audio_list: /rmt/work/irodoma/audio_asr/classification/ucf101/videos_with_audio.txt


DEBUG: 0
dbName: UCF101
global_seed: 25

# feature parameters
features:
    type: DT
    executable: /rmt8/mobot/external_packages/dense_trajectories/dense_trajectory_release_v1.2/release/DenseTrack
    libs: /rmt8/mobot/external_packages/opencv/lib/:/rmt8/mobot/external_packages/ffmpeg/ffmpeg_build/lib/ 
    descriptors: [mfcc25]
    L: 15 # trajectory length
    W: 5 # sampling stride
    N: 32 # neighbourhood size
    s: 2 # number of spatial cells
    t: 3 # number of temporal cells
    save2disk: 1
    # the following flag is experimental, use only with Hollywood2 dataset, and not in a parfor loop!
    use_disk: 0
    
# encoding parameters
encoding:
    type: BoVW # possible options are BoVW, vlad or fisher
    K: 2000 # MODIFY!!! number of visual words for either kmeans or gmm
    data_usage: 70000 # data used for codebook generation as percentage of TrainData
    pca_factor: 1
    num_seeds: 1 # number of k-means repetitions with different (random) initializations (seeds)

# spatio-temporal pyramids parameters    
#grids:
    #- {h: 1, v: 1, t: 1}
    #- {h: 3, v: 1, t: 1}
    #- {h: 2, v: 2, t: 1}
    #- {h: 1, v: 1, t: 2}
    #- {h: 3, v: 1, t: 2}
    #- {h: 2, v: 2, t: 2}

# classification parameters
classification:
    svm_cost: 100
    kernel: ChiSquared #linear ChiSquared
    combine: 0 
    combine_descriptors: [] # MODIFY!!! think possible combinations
    
# possible reusage of elements
reuse:
    features: 1

## states
# 0: nothing has been done
# 1: codebook has been generated
# 2: encodings have been computed
# 2.5: kernels have been computed (does not apply to Linear kernel)
# 3: SVMs have been trained
# 4: testinghas been done
state: 0

