
paths:
    root: /home/nick/Desktop/Experiments_ActionClassif
    db: /mobot_data1/ExtractedVideos
    db_data: /home/nick/Dropbox/Gesture/data
    code: /home/nick/Dropbox/Gesture/Code_v0.2
    yael: /home/nick/ExternalPackages/yael_v438/matlab
    LibSvm: /home/nick/ExternalPackages/libsvm-3.17_with_conversion_tool/matlab/
    features: /mobot_evaluation_data/features/harris3d/KTH

DEBUG: 0
dbName: MOBOT6a
global_seed: 25

# feature parameters
features:
    type: harris3d
    executable: /home/nick/ExternalPackages/stip-2.0-linux/bin/stipdet
    libs: /home/nick/ExternalPackages/opencv/lib
    descriptors: [HOG, HOF, HOGHOF]
    nplev: 3 # number of scales
    plev0: 0 # first scale
    szf: 18 # patch size's spatial factor
    tzf: 4 # patch size's temporal factor
    save2disk: 1
    
# encoding parameters
encoding:
    type: BoVW # possible options are BoVW, vlad or fisher
    K: 4000 # number of visual words for either kmeans or gmm
    data_usage: 100000 # data used for codebook generation as percentage of TrainData
    pca_factor: 1
    num_seeds: 1 # number of k-means repetitions with different (random) initializations (seeds)

# spatio-temporal pyramids parameters    
#grids: 
    #- {h: 1, v: 1, t: 1}
    #- {h: 3, v: 1, t: 1}
    #- {h: 2, v: 2, t: 1}
    #- {h: 1, v: 1, t: 2}
    #- {h: 3, v: 1, t: 2}
    #- {h: 2, v: 2, t: 2}

# classification parameters
classification:
    svm_cost: 100
    kernel: ChiSquared
    combine: 0
    
# possible reusage of elements
reuse:
    features: 1

## states
# 0: nothing has been done
# 1: codebook has been generated
# 2: encodings have been computed
# 2.5: kernels have been computed (does not apply to Linear kernel)
# 3: SVMs have been trained
# 4: testinghas been done
state: 0

